/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAdminRouteImport } from './routes/_app/_admin'
import { Route as AppAdminFamiliasRouteImport } from './routes/_app/_admin.familias'
import { Route as AppAdminAcoesRouteImport } from './routes/_app/_admin.acoes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminFamiliasRoute = AppAdminFamiliasRouteImport.update({
  id: '/familias',
  path: '/familias',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAcoesRoute = AppAdminAcoesRouteImport.update({
  id: '/acoes',
  path: '/acoes',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/acoes': typeof AppAdminAcoesRoute
  '/familias': typeof AppAdminFamiliasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/acoes': typeof AppAdminAcoesRoute
  '/familias': typeof AppAdminFamiliasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/_admin': typeof AppAdminRouteWithChildren
  '/_app/_admin/acoes': typeof AppAdminAcoesRoute
  '/_app/_admin/familias': typeof AppAdminFamiliasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/acoes' | '/familias'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/acoes' | '/familias'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/_admin'
    | '/_app/_admin/acoes'
    | '/_app/_admin/familias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_admin': {
      id: '/_app/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_admin/familias': {
      id: '/_app/_admin/familias'
      path: '/familias'
      fullPath: '/familias'
      preLoaderRoute: typeof AppAdminFamiliasRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/acoes': {
      id: '/_app/_admin/acoes'
      path: '/acoes'
      fullPath: '/acoes'
      preLoaderRoute: typeof AppAdminAcoesRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAcoesRoute: typeof AppAdminAcoesRoute
  AppAdminFamiliasRoute: typeof AppAdminFamiliasRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAcoesRoute: AppAdminAcoesRoute,
  AppAdminFamiliasRoute: AppAdminFamiliasRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
