/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as AcaoIdRouteImport } from './routes/acao.$id'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppAdminRouteImport } from './routes/_app/_admin'
import { Route as AppAdminTiposUserRouteImport } from './routes/_app/_admin.tipos-user'
import { Route as AppAdminStyleGuideRouteImport } from './routes/_app/_admin.style-guide'
import { Route as AppAdminServicosRouteImport } from './routes/_app/_admin.servicos'
import { Route as AppAdminSecurityRouteImport } from './routes/_app/_admin.security'
import { Route as AppAdminProjetosRouteImport } from './routes/_app/_admin.projetos'
import { Route as AppAdminParticipantesRouteImport } from './routes/_app/_admin.participantes'
import { Route as AppAdminLocalizacoesRouteImport } from './routes/_app/_admin.localizacoes'
import { Route as AppAdminFamiliasRouteImport } from './routes/_app/_admin.familias'
import { Route as AppAdminEmailsRouteImport } from './routes/_app/_admin.emails'
import { Route as AppAdminEliminadosRouteImport } from './routes/_app/_admin.eliminados'
import { Route as AppAdminDuplicadosRouteImport } from './routes/_app/_admin.duplicados'
import { Route as AppAdminDashboardRouteImport } from './routes/_app/_admin.dashboard'
import { Route as AppAdminCurriculosRouteImport } from './routes/_app/_admin.curriculos'
import { Route as AppAdminBolsasTransporteRouteImport } from './routes/_app/_admin.bolsas-transporte'
import { Route as AppAdminAtividadesRouteImport } from './routes/_app/_admin.atividades'
import { Route as AppAdminAcoesRouteImport } from './routes/_app/_admin.acoes'
import { Route as AppAdminServicosColaboradorIdRouteImport } from './routes/_app/_admin.servicos.colaborador.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AcaoIdRoute = AcaoIdRouteImport.update({
  id: '/acao/$id',
  path: '/acao/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTiposUserRoute = AppAdminTiposUserRouteImport.update({
  id: '/tipos-user',
  path: '/tipos-user',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminStyleGuideRoute = AppAdminStyleGuideRouteImport.update({
  id: '/style-guide',
  path: '/style-guide',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminServicosRoute = AppAdminServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSecurityRoute = AppAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminProjetosRoute = AppAdminProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminParticipantesRoute = AppAdminParticipantesRouteImport.update({
  id: '/participantes',
  path: '/participantes',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLocalizacoesRoute = AppAdminLocalizacoesRouteImport.update({
  id: '/localizacoes',
  path: '/localizacoes',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFamiliasRoute = AppAdminFamiliasRouteImport.update({
  id: '/familias',
  path: '/familias',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminEmailsRoute = AppAdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminEliminadosRoute = AppAdminEliminadosRouteImport.update({
  id: '/eliminados',
  path: '/eliminados',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDuplicadosRoute = AppAdminDuplicadosRouteImport.update({
  id: '/duplicados',
  path: '/duplicados',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCurriculosRoute = AppAdminCurriculosRouteImport.update({
  id: '/curriculos',
  path: '/curriculos',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBolsasTransporteRoute =
  AppAdminBolsasTransporteRouteImport.update({
    id: '/bolsas-transporte',
    path: '/bolsas-transporte',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminAtividadesRoute = AppAdminAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAcoesRoute = AppAdminAcoesRouteImport.update({
  id: '/acoes',
  path: '/acoes',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminServicosColaboradorIdRoute =
  AppAdminServicosColaboradorIdRouteImport.update({
    id: '/colaborador/$id',
    path: '/colaborador/$id',
    getParentRoute: () => AppAdminServicosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/resultados': typeof ResultadosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/perfil': typeof AppPerfilRoute
  '/acao/$id': typeof AcaoIdRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/acoes': typeof AppAdminAcoesRoute
  '/atividades': typeof AppAdminAtividadesRoute
  '/bolsas-transporte': typeof AppAdminBolsasTransporteRoute
  '/curriculos': typeof AppAdminCurriculosRoute
  '/dashboard': typeof AppAdminDashboardRoute
  '/duplicados': typeof AppAdminDuplicadosRoute
  '/eliminados': typeof AppAdminEliminadosRoute
  '/emails': typeof AppAdminEmailsRoute
  '/familias': typeof AppAdminFamiliasRoute
  '/localizacoes': typeof AppAdminLocalizacoesRoute
  '/participantes': typeof AppAdminParticipantesRoute
  '/projetos': typeof AppAdminProjetosRoute
  '/security': typeof AppAdminSecurityRoute
  '/servicos': typeof AppAdminServicosRouteWithChildren
  '/style-guide': typeof AppAdminStyleGuideRoute
  '/tipos-user': typeof AppAdminTiposUserRoute
  '/servicos/colaborador/$id': typeof AppAdminServicosColaboradorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/resultados': typeof ResultadosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/perfil': typeof AppPerfilRoute
  '/acao/$id': typeof AcaoIdRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/acoes': typeof AppAdminAcoesRoute
  '/atividades': typeof AppAdminAtividadesRoute
  '/bolsas-transporte': typeof AppAdminBolsasTransporteRoute
  '/curriculos': typeof AppAdminCurriculosRoute
  '/dashboard': typeof AppAdminDashboardRoute
  '/duplicados': typeof AppAdminDuplicadosRoute
  '/eliminados': typeof AppAdminEliminadosRoute
  '/emails': typeof AppAdminEmailsRoute
  '/familias': typeof AppAdminFamiliasRoute
  '/localizacoes': typeof AppAdminLocalizacoesRoute
  '/participantes': typeof AppAdminParticipantesRoute
  '/projetos': typeof AppAdminProjetosRoute
  '/security': typeof AppAdminSecurityRoute
  '/servicos': typeof AppAdminServicosRouteWithChildren
  '/style-guide': typeof AppAdminStyleGuideRoute
  '/tipos-user': typeof AppAdminTiposUserRoute
  '/servicos/colaborador/$id': typeof AppAdminServicosColaboradorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/resultados': typeof ResultadosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/_admin': typeof AppAdminRouteWithChildren
  '/_app/perfil': typeof AppPerfilRoute
  '/acao/$id': typeof AcaoIdRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/_app/_admin/acoes': typeof AppAdminAcoesRoute
  '/_app/_admin/atividades': typeof AppAdminAtividadesRoute
  '/_app/_admin/bolsas-transporte': typeof AppAdminBolsasTransporteRoute
  '/_app/_admin/curriculos': typeof AppAdminCurriculosRoute
  '/_app/_admin/dashboard': typeof AppAdminDashboardRoute
  '/_app/_admin/duplicados': typeof AppAdminDuplicadosRoute
  '/_app/_admin/eliminados': typeof AppAdminEliminadosRoute
  '/_app/_admin/emails': typeof AppAdminEmailsRoute
  '/_app/_admin/familias': typeof AppAdminFamiliasRoute
  '/_app/_admin/localizacoes': typeof AppAdminLocalizacoesRoute
  '/_app/_admin/participantes': typeof AppAdminParticipantesRoute
  '/_app/_admin/projetos': typeof AppAdminProjetosRoute
  '/_app/_admin/security': typeof AppAdminSecurityRoute
  '/_app/_admin/servicos': typeof AppAdminServicosRouteWithChildren
  '/_app/_admin/style-guide': typeof AppAdminStyleGuideRoute
  '/_app/_admin/tipos-user': typeof AppAdminTiposUserRoute
  '/_app/_admin/servicos/colaborador/$id': typeof AppAdminServicosColaboradorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/resultados'
    | '/sitemap.xml'
    | '/perfil'
    | '/acao/$id'
    | '/convite/$token'
    | '/acoes'
    | '/atividades'
    | '/bolsas-transporte'
    | '/curriculos'
    | '/dashboard'
    | '/duplicados'
    | '/eliminados'
    | '/emails'
    | '/familias'
    | '/localizacoes'
    | '/participantes'
    | '/projetos'
    | '/security'
    | '/servicos'
    | '/style-guide'
    | '/tipos-user'
    | '/servicos/colaborador/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/resultados'
    | '/sitemap.xml'
    | '/perfil'
    | '/acao/$id'
    | '/convite/$token'
    | '/acoes'
    | '/atividades'
    | '/bolsas-transporte'
    | '/curriculos'
    | '/dashboard'
    | '/duplicados'
    | '/eliminados'
    | '/emails'
    | '/familias'
    | '/localizacoes'
    | '/participantes'
    | '/projetos'
    | '/security'
    | '/servicos'
    | '/style-guide'
    | '/tipos-user'
    | '/servicos/colaborador/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/resultados'
    | '/sitemap.xml'
    | '/_app/_admin'
    | '/_app/perfil'
    | '/acao/$id'
    | '/convite/$token'
    | '/_app/_admin/acoes'
    | '/_app/_admin/atividades'
    | '/_app/_admin/bolsas-transporte'
    | '/_app/_admin/curriculos'
    | '/_app/_admin/dashboard'
    | '/_app/_admin/duplicados'
    | '/_app/_admin/eliminados'
    | '/_app/_admin/emails'
    | '/_app/_admin/familias'
    | '/_app/_admin/localizacoes'
    | '/_app/_admin/participantes'
    | '/_app/_admin/projetos'
    | '/_app/_admin/security'
    | '/_app/_admin/servicos'
    | '/_app/_admin/style-guide'
    | '/_app/_admin/tipos-user'
    | '/_app/_admin/servicos/colaborador/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResultadosRoute: typeof ResultadosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AcaoIdRoute: typeof AcaoIdRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acao/$id': {
      id: '/acao/$id'
      path: '/acao/$id'
      fullPath: '/acao/$id'
      preLoaderRoute: typeof AcaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_admin': {
      id: '/_app/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_admin/tipos-user': {
      id: '/_app/_admin/tipos-user'
      path: '/tipos-user'
      fullPath: '/tipos-user'
      preLoaderRoute: typeof AppAdminTiposUserRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/style-guide': {
      id: '/_app/_admin/style-guide'
      path: '/style-guide'
      fullPath: '/style-guide'
      preLoaderRoute: typeof AppAdminStyleGuideRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/servicos': {
      id: '/_app/_admin/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AppAdminServicosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/security': {
      id: '/_app/_admin/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppAdminSecurityRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/projetos': {
      id: '/_app/_admin/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AppAdminProjetosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/participantes': {
      id: '/_app/_admin/participantes'
      path: '/participantes'
      fullPath: '/participantes'
      preLoaderRoute: typeof AppAdminParticipantesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/localizacoes': {
      id: '/_app/_admin/localizacoes'
      path: '/localizacoes'
      fullPath: '/localizacoes'
      preLoaderRoute: typeof AppAdminLocalizacoesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/familias': {
      id: '/_app/_admin/familias'
      path: '/familias'
      fullPath: '/familias'
      preLoaderRoute: typeof AppAdminFamiliasRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/emails': {
      id: '/_app/_admin/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof AppAdminEmailsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/eliminados': {
      id: '/_app/_admin/eliminados'
      path: '/eliminados'
      fullPath: '/eliminados'
      preLoaderRoute: typeof AppAdminEliminadosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/duplicados': {
      id: '/_app/_admin/duplicados'
      path: '/duplicados'
      fullPath: '/duplicados'
      preLoaderRoute: typeof AppAdminDuplicadosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/dashboard': {
      id: '/_app/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/curriculos': {
      id: '/_app/_admin/curriculos'
      path: '/curriculos'
      fullPath: '/curriculos'
      preLoaderRoute: typeof AppAdminCurriculosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/bolsas-transporte': {
      id: '/_app/_admin/bolsas-transporte'
      path: '/bolsas-transporte'
      fullPath: '/bolsas-transporte'
      preLoaderRoute: typeof AppAdminBolsasTransporteRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/atividades': {
      id: '/_app/_admin/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AppAdminAtividadesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/acoes': {
      id: '/_app/_admin/acoes'
      path: '/acoes'
      fullPath: '/acoes'
      preLoaderRoute: typeof AppAdminAcoesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/servicos/colaborador/$id': {
      id: '/_app/_admin/servicos/colaborador/$id'
      path: '/colaborador/$id'
      fullPath: '/servicos/colaborador/$id'
      preLoaderRoute: typeof AppAdminServicosColaboradorIdRouteImport
      parentRoute: typeof AppAdminServicosRoute
    }
  }
}

interface AppAdminServicosRouteChildren {
  AppAdminServicosColaboradorIdRoute: typeof AppAdminServicosColaboradorIdRoute
}

const AppAdminServicosRouteChildren: AppAdminServicosRouteChildren = {
  AppAdminServicosColaboradorIdRoute: AppAdminServicosColaboradorIdRoute,
}

const AppAdminServicosRouteWithChildren =
  AppAdminServicosRoute._addFileChildren(AppAdminServicosRouteChildren)

interface AppAdminRouteChildren {
  AppAdminAcoesRoute: typeof AppAdminAcoesRoute
  AppAdminAtividadesRoute: typeof AppAdminAtividadesRoute
  AppAdminBolsasTransporteRoute: typeof AppAdminBolsasTransporteRoute
  AppAdminCurriculosRoute: typeof AppAdminCurriculosRoute
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminDuplicadosRoute: typeof AppAdminDuplicadosRoute
  AppAdminEliminadosRoute: typeof AppAdminEliminadosRoute
  AppAdminEmailsRoute: typeof AppAdminEmailsRoute
  AppAdminFamiliasRoute: typeof AppAdminFamiliasRoute
  AppAdminLocalizacoesRoute: typeof AppAdminLocalizacoesRoute
  AppAdminParticipantesRoute: typeof AppAdminParticipantesRoute
  AppAdminProjetosRoute: typeof AppAdminProjetosRoute
  AppAdminSecurityRoute: typeof AppAdminSecurityRoute
  AppAdminServicosRoute: typeof AppAdminServicosRouteWithChildren
  AppAdminStyleGuideRoute: typeof AppAdminStyleGuideRoute
  AppAdminTiposUserRoute: typeof AppAdminTiposUserRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAcoesRoute: AppAdminAcoesRoute,
  AppAdminAtividadesRoute: AppAdminAtividadesRoute,
  AppAdminBolsasTransporteRoute: AppAdminBolsasTransporteRoute,
  AppAdminCurriculosRoute: AppAdminCurriculosRoute,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminDuplicadosRoute: AppAdminDuplicadosRoute,
  AppAdminEliminadosRoute: AppAdminEliminadosRoute,
  AppAdminEmailsRoute: AppAdminEmailsRoute,
  AppAdminFamiliasRoute: AppAdminFamiliasRoute,
  AppAdminLocalizacoesRoute: AppAdminLocalizacoesRoute,
  AppAdminParticipantesRoute: AppAdminParticipantesRoute,
  AppAdminProjetosRoute: AppAdminProjetosRoute,
  AppAdminSecurityRoute: AppAdminSecurityRoute,
  AppAdminServicosRoute: AppAdminServicosRouteWithChildren,
  AppAdminStyleGuideRoute: AppAdminStyleGuideRoute,
  AppAdminTiposUserRoute: AppAdminTiposUserRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppPerfilRoute: typeof AppPerfilRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppPerfilRoute: AppPerfilRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResultadosRoute: ResultadosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AcaoIdRoute: AcaoIdRoute,
  ConviteTokenRoute: ConviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
